config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  resource :garden do
    get :flowers
    get :birds
    get :path

    post :validate_step
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :flowers, presence: true
  validates :birds, presence: true
  validates :path, presence: true
end

app/models/garden_wizard/base_form.rb
module GardenWizard
  class BaseForm
    include ActiveModel::Model

    # Writing as well as reading necessary for the controller to assign params to this
    attr_accessor :garden

    # The Splat operator, in this context, converts the array into positional arguments to 'delegate'
    # This is useful when you want to pass in several parameters to a method, but you don't know in advance how many there will be
    delegate *Garden.attribute_names.map { |attr| [attr, "#{attr}="] }.flatten, to: :garden

    def initialize(garden_attributes = {})
      @garden = Garden.new(garden_attributes)
    end
  end
end

app/models/garden_wizard/birds_form.rb
# frozen_string_literal: true

module GardenWizard
  class BirdsForm < BaseForm
    validates :birds, presence: true
  end
end

app/models/garden_wizard/flowers_form.rb
# frozen_string_literal: true

module GardenWizard
  class FlowersForm < BaseForm
    validates :flowers, presence: true
  end
end

app/models/garden_wizard/path_form.rb
# frozen_string_literal: true

module GardenWizard
  class PathForm < BaseForm
    validates :path, presence: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
# frozen_string_literal: true

class GardensController < ApplicationController
  WIZARD_STEPS = %w[ flowers birds path ].freeze

  def flowers
    # Instantiate a new form model for this step, passing in a new garden as the basis
    @garden_form = GardenWizard::FlowersForm.new(session[:garden_params])
  end

  def birds
    @garden_form = GardenWizard::BirdsForm.new(session[:garden_params])
  end

  def path
    @garden_form = GardenWizard::PathForm.new(session[:garden_params])
  end

  def validate_step
    # Build a form model, purely for validation purposes, based off all attributes saved from previous steps
    # (Or nil if the first step)
    current_step_name = params[:current_step]  # e.g. 'flowers'

    case current_step_name
    when "flowers"
      garden_form_class = GardenWizard::FlowersForm
    when "birds"
      garden_form_class = GardenWizard::BirdsForm
    else
      garden_form_class = GardenWizard::PathForm
    end

    @garden_form = garden_form_class.new(session[:garden_params])

    # Populate the model underlying the form model with the latest, additional parameters
    # These shouldn't clash with any existing attributes set on the model, as those should have come from previous steps and therefore
    # were for different attribute names
    @garden_form.garden.attributes = garden_params

    # Store every attribute, including those just submitted, in the wizard in the session
    session[:garden_params] = @garden_form.garden.attributes

    # Requires each form view to have a hidden field for this
    next_step_name = get_next_step(current_step_name)

    if @garden_form.valid?
      if next_step_name
        redirect_to action: next_step_name
      else
        create
        return
      end
    else
      render current_step_name
    end
  end

  def create
    if @garden_form.garden.save
      session[:garden_params] = nil
      redirect_to root_path
    else
      render WIZARD_STEPS.first
    end
  end

  private

  # Rails detects params from sources including POST parameters and query parameters
  # It puts them into a hash-like object, params
  def garden_params
    params.require(:garden_form).permit(:flowers, :birds, :path)
  end

  def get_next_step(current_step_name)
    WIZARD_STEPS[WIZARD_STEPS.index(current_step_name) + 1]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @garden_count = Garden.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/birds.html.erb
<p><%= "Here's your garden! #{@garden_form.to_json}" %></p>

<p><%= "Here's your session! #{session.to_hash}" %></p>

<%= form_for(@garden_form, as: :garden_form, url: validate_step_garden_path) do |form| %>
  <%= hidden_field_tag :current_step, 'birds' %>

  <%= form.text_field :birds %>
  <%= form.submit "Save" %>
<% end %>

app/views/gardens/flowers.html.erb
<%= "Here's your garden! #{@garden_form.to_json}" %>

<%= form_for(@garden_form, as: :garden_form, url: validate_step_garden_path) do |form| %>
  <%= hidden_field_tag :current_step, 'flowers' %>

  <%= form.text_field :flowers %>
  <%= form.submit "Save" %>
<% end %>

app/views/gardens/path.html.erb
<%= "Here's your garden! #{@garden_form.to_json}" %>

<%= form_for(@garden_form, as: :garden_form, url: validate_step_garden_path) do |form| %>
  <%= hidden_field_tag :current_step, 'path' %>
  
  <%= form.text_field :path %>
  <%= form.submit "Save" %>
<% end %>

app/views/home/index.html.erb
<h2>You're HOME now</h2>

<h3><%= @garden_count %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WizardWoo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>